---
title: "R Notebook"
output: html_notebook
---
```{r}
library(data.table)

```



```{r}
data1 <- fread("data/2018_S1_NB_FER.txt", header = TRUE, sep = "\t")  
data2 <- fread("data/2018_S2_NB_FER.txt", header = TRUE, sep = "\t")  
data3 <- fread("data/2019_S1_NB_FER.txt", header = TRUE, sep = "\t")
data4 <- fread("data/2019_S2_NB_FER.txt", header = TRUE, sep = "\t")
data5 <- fread("data/2020_S1_NB_FER.txt", header = TRUE, sep = "\t")
data6 <- fread("data/2020_S2_NB_FER.txt", header = TRUE, sep = "\t")
data7 <- fread("data/2021_S1_NB_FER.txt", header = TRUE, sep = "\t")
data8 <- fread("data/2021_S2_NB_FER.txt", header = TRUE, sep = "\t")
data9 <- fread("data/2022_S1_NB_FER.txt", header = TRUE, sep = "\t")
data10 <- fread("data/2022_S2_NB_FER.txt", header = TRUE, sep = ";")
```


```{r}
# Store all data tables in a list
data_list <- list(data1, data2, data3, data4, data5, data6, data7, data8, data9, data10)

# Use lapply to print the head of each dataset
lapply(seq_along(data_list), function(i) {
  cat("\n--- Head of dataset", i, "---\n")
  print(head(data_list[[i]]))
})

```

```{r}
# Store all data tables in a list
data_list <- list(data1, data2, data3, data4, data5, data6, data7, data8, data9, data10)

# Use lapply to print the column names and types
lapply(seq_along(data_list), function(i) {
  cat("\n--- Structure of dataset", i, "---\n")
  print(str(data_list[[i]]))
})

```


```{r}
data11 <- fread("data/data-rf-2023-s1.csv", header = TRUE)
head(data11)
# Optionally, you can get just the column names and their respective types:
column_types <- sapply(data11, class)
print(column_types)
```


```{r}


# Convert JOUR column from IDate to Date
data11[, JOUR := as.Date(JOUR)]

# Verify the change
str(data11)


```


```{r}
# Store all data tables in a list
data_list <- list(data1, data2, data3, data4, data5, data6, data7, data8, data9, data10)

# Convert 'JOUR' column to Date type for all datasets
data_list <- lapply(data_list, function(dataset) {
  dataset$JOUR <- as.Date(dataset$JOUR, format = "%d/%m/%Y")
  return(dataset)
})

# Print the head of each dataset
lapply(seq_along(data_list), function(i) {
  cat("\n--- Head of dataset", i, "---\n")
  print(head(data_list[[i]]))
  
  
})


```


```{r}
# Convert the 'JOUR' column from IDate to Date
data11$JOUR <- as.Date(data11$JOUR)

# Check the column types again to confirm the change
column_types <- sapply(data11, class)
print(column_types)
```


```{r}
# Combine the data list and data11
combined_data <- rbindlist(c(data_list, list(data11)), fill = TRUE)
# Save the combined data to a CSV file
write.csv(combined_data, "combined_data.csv", row.names = FALSE)

```





```{r}
str(combined_data)  # Gives structure of the dataset including column names, types, and a preview 
```
 data correction and visulisation
 
```{r}
# Assuming your data.table is named dt
# Convert CODE_STIF_RES and CODE_STIF_ARRET to integer in place
combined_data[, CODE_STIF_RES := as.integer(CODE_STIF_RES)]
combined_data[, CODE_STIF_ARRET := as.integer(CODE_STIF_ARRET)]


# Vérification des types des colonnes
str(combined_data)

```

```{r}
head(combined_data)
```

Missing Values in All Numeric Columns

```{r}
# Identify numeric columns
numeric_cols <- names(combined_data)[sapply(combined_data, is.numeric)]

# Check for missing values in numeric columns
missing_summary <- sapply(numeric_cols, function(col) sum(is.na(combined_data[[col]])))

# Print the summary
print("Missing values in numeric columns:")
print(missing_summary)
```

```{r}
missing_rate_res <- sum(is.na(combined_data$CODE_STIF_RES)) / nrow(combined_data)
missing_rate_arret <- sum(is.na(combined_data$CODE_STIF_ARRET)) / nrow(combined_data)
print(paste("Missing rate for CODE_STIF_RES:", missing_rate_res))
print(paste("Missing rate for CODE_STIF_ARRET:", missing_rate_arret))

```

```{r}
# Remove rows with any NA values
dt<- na.omit(combined_data)

# Verify the number of rows before and after removal
nrow(combined_data)  # Original number of rows
nrow(dt)  # Number of rows after removal

```


```{r}
# Count occurrences of '?' in LIBELLE_ARRET
libelle_arret_missing <- sum(dt$LIBELLE_ARRET == "?", na.rm = TRUE)
print(paste("Occurrences of '?' in LIBELLE_ARRET:", libelle_arret_missing))

# Count occurrences of '?' in CATEGORIE_TITRE
categorie_titre_missing <- sum(dt$CATEGORIE_TITRE == "?", na.rm = TRUE)
categorie_titre_percentage <- (categorie_titre_missing / nrow(dt)) * 100
print(paste("Occurrences of '?' in CATEGORIE_TITRE:", categorie_titre_missing))
print(paste("Percentage of '?' in CATEGORIE_TITRE:", round(categorie_titre_percentage, 2), "%"))


```
```{r}
dt_cleaned <- dt[dt$CATEGORIE_TITRE != "?", ]
# Verify the number of rows before and after removal
nrow(dt_cleaned)  # Original number of rows
nrow(dt)  # Number of rows after removal
```
Outliers

 
```{r}
# Boxplot for each numerical column
boxplot(dt_cleaned$CODE_STIF_TRNS, main = "Boxplot of NB_VALD", ylab = "NB_VALD")
```
checking for outliers CODE_STIF_RES column 


```{r}
boxplot(dt_cleaned$CODE_STIF_RES, main = "Boxplot of CODE_STIF_RES ", ylab = "CODE_STIF_RES ")

```
```{r}
boxplot(dt_cleaned$CODE_STIF_ARRET, main = "Boxplot of CODE_STIF_RES ", ylab = "CODE_STIF_ARRET ")

```
```{r}
boxplot(dt_cleaned$ID_REFA_LDA, main = "Boxplot of ID_REFA_LDA ", ylab = "ID_REFA_LDA ")
```

```{r}
boxplot(dt_cleaned$NB_VALD, main = "Boxplot of NB_VALD  ", ylab = "NB_VALD")
```

